// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdumbocpgzcvaohexswc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdW1ib2NwZ3pjdmFvaGV4c3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODkyMTEsImV4cCI6MjA3MjU2NTIxMX0.yPXS53fhihhHA0iTyTiVKAq3Ca8J4Su64sntr8fG9R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});